<?php
/* Copyright (C) 2026 SLY Custom
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 */

/**
 * SLY core patch tool: list the sly24.0-*.patch series, show live status
 * (not applied / applied / conflict) and apply them from the browser.
 *
 * Status detection relies on reverse dry-runs: a patch is "applied" when the
 * reverse patch applies cleanly. Applying first backs up every touched file
 * into documents/slycustom/patch-backups/ (per-patch stable backup, per-session
 * audit snapshot, per-patch tar.gz pack, cross-patch bundle tar.gz).
 *
 * Reset / rollback sources are entirely local: per-patch backup dirs and
 * the bundle tar.gz. No git checkout, no network download — the operator
 * is the only source of bytes. The one escape hatch for a tree that has
 * drifted with no backups left (all patches Conflict + empty per-patch
 * layer, as reported on d-test) is the operator-driven upload card: build
 * a clean 24.0.1 tar.gz off-host from the downloadable target list and
 * upload it; the tool restores htdocs and seeds the per-patch layer.
 * Admin only; CSRF-protected; patch name validated against a whitelist.
 */

$res = 0;
if (!$res && file_exists(__DIR__.'/../../main.inc.php')) {
	$res = @include __DIR__.'/../../main.inc.php';
}
if (!$res && file_exists(__DIR__.'/../main.inc.php')) {
	$res = @include __DIR__.'/../main.inc.php';
}
if (!$res && file_exists(__DIR__.'/../../../main.inc.php')) {
	$res = @include __DIR__.'/../../../main.inc.php';
}
if (!$res) {
	die('Include of main.inc.php failed for SLY Custom patches.php');
}

require_once DOL_DOCUMENT_ROOT.'/core/lib/admin.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/files.lib.php';

if (!$user->admin) {
	accessforbidden();
	exit;
}

$langs->loadLangs(array("admin", "slycustom@slycustom"));

// The sly24.0-* series targets official 24.x only.
$versionOk = (version_compare(DOL_VERSION, '24.0.0', '>=') && version_compare(DOL_VERSION, '25.0.0', '<'));

// Ordered patch list (apply order mirrors patches/APPLY-ON-24.md).
$PATCHES = array(
	'core' => 'SlyPatchDescCore',
	'menu-parent-match' => 'SlyPatchDescMenuParentMatch',
	'compta-multicurrency' => 'SlyPatchDescCompta',
	'remx' => 'SlyPatchDescRemx',
	'commande' => 'SlyPatchDescCommande',
	'fourn-linkedobject' => 'SlyPatchDescFourn',
	'comm-propal-linkedobject' => 'SlyPatchDescCommPropal',
	'admin' => 'SlyPatchDescAdmin',
	'api' => 'SlyPatchDescApi',
	'misc-cron-other' => 'SlyPatchDescMiscCron',
	'other-modules' => 'SlyPatchDescOtherModules',
	'bank-treso' => 'SlyPatchDescBankTreso',
	'invoice-list-source-order-position' => 'SlyPatchDescInvoiceListPos',
	'supplier-invoice-list-source-order-position' => 'SlyPatchDescSupplierInvoiceListPos',
	'facture-pdf-fallback' => 'SlyPatchDescFacturePdf',
	'accountancy-sfrs' => 'SlyPatchDescAccountancySfrs',
	'langs' => 'SlyPatchDescLangs',
);

/**
 * Build the shell command fragments for status checking and applying.
 * Prefers git apply (atomic); falls back to the POSIX patch command.
 *
 * The git invocation carries `-c safe.directory=<DOL_DOCUMENT_ROOT>`:
 * when htdocs is a git checkout owned by a different user than the
 * php-fpm process (typical for /home/<user> deployments), git >= 2.35.2
 * refuses to run with "detected dubious ownership" — which made every
 * status check fail and every patch show "conflict". Older git versions
 * ignore the unknown config key, so this is safe everywhere.
 *
 * @return array{engine:string,check:string,checkrev:string,apply:string} Command templates with %s placeholders
 */
function slyPatchEngine()
{
	$git = trim((string) shell_exec('command -v git 2>/dev/null'));
	if ($git !== '') {
		$safe = '-c safe.directory='.escapeshellarg(str_replace('\\', '/', DOL_DOCUMENT_ROOT));
		// -p2 strips "a/htdocs/" — the patches are generated by
		// gen_sly24_patches.sh from the REPO ROOT (parent of htdocs), so
		// every header reads a/htdocs/<path>. We run inside
		// DOL_DOCUMENT_ROOT (= htdocs), hence two levels. -p1 made the
		// engine look for <htdocs>/htdocs/<path> (d-test2, 2026-09-22:
		// "error: htdocs/core/... No such file or directory").
		return array(
			'engine' => 'git apply',
			'check' => "git $safe apply --check -p2 --ignore-whitespace %s 2>&1",
			'checkrev' => "git $safe apply --check -R -p2 --ignore-whitespace %s 2>&1",
			'apply' => "git $safe apply -p2 --ignore-whitespace %s 2>&1",
		);
	}
	return array(
		'engine' => 'patch --batch --forward',
		'check' => 'patch --batch --dry-run --forward -p2 -i %s 2>&1',
		'checkrev' => 'patch --batch --dry-run -R -p2 -i %s 2>&1',
		'apply' => 'patch --batch --forward -p2 -i %s 2>&1',
	);
}

/**
 * Return a LF-normalised copy of a patch file. A patch saved on Windows
 * with CRLF endings cannot be applied by `git apply` on Linux: the CR
 * becomes part of the `+++ b/<file>` header and of every context line,
 * so BOTH the forward and the reverse dry-runs fail and the patch shows
 * "conflict" on a perfectly clean tree — the exact failure d-test and
 * d-test2 hit (2026-09-22, all 17 patches conflict on a pristine 24.0.1).
 *
 * When the file already has no CR the original path is returned and no
 * temp file is written. Otherwise a normalised copy is written under
 * DOL_DATA_ROOT/slycustom/patch-backups/.norm_<basename> (stable name,
 * idempotent overwrite, never cleaned up — a few dozen KB at worst).
 *
 * @param  string $patchfile Absolute path to the .patch file
 * @return string Path to feed the engine (original or normalised temp)
 */
function slyPatchNormalizePatchFile($patchfile)
{
	$content = @file_get_contents($patchfile);
	if ($content === false || strpos($content, "\r") === false) {
		return $patchfile;
	}
	$out = DOL_DATA_ROOT.'/slycustom/patch-backups/.norm_'.basename($patchfile);
	if (!slyPatchEnsureDir(dirname($out))) {
		return $patchfile; // cannot stage a normalised copy — engine will report
	}
	file_put_contents($out, str_replace("\r\n", "\n", $content));
	return $out;
}

/**
 * dol_mkdir() semantics: 0 = already exists, <0 = KO, >0 = created.
 * Code that treated its return as boolean (`!dol_mkdir($dir)`) misread
 * "already exists" (0) as failure — the first Create-bundle worked, and
 * every later pack/bundle build failed with a bogus "could not create
 * dir" (d-test2, 2026-09-22). This wrapper is truth-proof.
 *
 * @param  string $dir Absolute directory path
 * @return bool  True when $dir exists (pre-existing or just created)
 */
function slyPatchEnsureDir($dir)
{
	if (is_dir($dir)) {
		return true;
	}
	dol_mkdir($dir);
	return is_dir($dir);
}

/**
 * Detect the status of one patch: 'applied', 'notapplied', 'conflict' or 'missing'.
 *
 * @param  string $patchfile Absolute path to the .patch file
 * @param  array  $engine    Result of slyPatchEngine()
 * @return array  array('status'=>string, 'output'=>string)
 */
function slyPatchStatus($patchfile, $engine)
{
	if (!is_readable($patchfile)) {
		return array('status' => 'missing', 'output' => '');
	}
	// Feed the engine an LF-normalised copy when the stored patch has CRLF
	// endings — see slyPatchNormalizePatchFile().
	$patchfile = slyPatchNormalizePatchFile($patchfile);
	$cmd = 'cd '.escapeshellarg(DOL_DOCUMENT_ROOT).' && '.sprintf($engine['checkrev'], escapeshellarg($patchfile));
	exec($cmd, $out, $ret);
	if ($ret === 0) {
		return array('status' => 'applied', 'output' => '');
	}
	$cmd = 'cd '.escapeshellarg(DOL_DOCUMENT_ROOT).' && '.sprintf($engine['check'], escapeshellarg($patchfile));
	exec($cmd, $out2, $ret2);
	if ($ret2 === 0) {
		return array('status' => 'notapplied', 'output' => '');
	}
	return array('status' => 'conflict', 'output' => implode("\n", array_merge($out, $out2)));
}

/**
 * Session-cached status wrapper. A full sweep costs 2 exec() per patch
 * (reverse + forward dry-run) — 34 process spawns per PAGE VIEW on the
 * 17-patch tree, which throttled the d-test2 shared host to near-
 * unavailability during one-by-one applies (2026-09). Rows are cached for
 * 10 minutes; single-patch actions overwrite their own row with the
 * deterministic outcome; bulk actions drop the whole cache; the Rescan
 * button (?rescan=1) forces a fresh sweep.
 *
 * @param  string $name      Patch short name
 * @param  string $patchfile Absolute path to the .patch file
 * @param  array  $engine    Result of slyPatchEngine()
 * @param  bool   $force     Bypass the cache for this row
 * @return array  array('status'=>string, 'output'=>string)
 */
function slyPatchStatusCached($name, $patchfile, $engine, $force = false)
{
	if (!isset($_SESSION['slypatch_stcache']) || !is_array($_SESSION['slypatch_stcache'])) {
		$_SESSION['slypatch_stcache'] = array('t' => 0, 'st' => array());
	}
	$c = &$_SESSION['slypatch_stcache'];
	if (!$force && $c['t'] > 0 && (time() - $c['t']) < 600 && isset($c['st'][$name])) {
		return $c['st'][$name];
	}
	$st = slyPatchStatus($patchfile, $engine);
	$c['st'][$name] = $st;
	return $st;
}

/**
 * Start a status sweep: if the cached sweep is older than the TTL, reset it
 * so the rows computed during THIS sweep count as one fresh snapshot (the
 * per-row wrapper above only fills missing rows — without this reset a
 * stale cache would re-run every row on every view).
 *
 * @return void
 */
function slyPatchStatusSweepBegin()
{
	if (!isset($_SESSION['slypatch_stcache']) || !is_array($_SESSION['slypatch_stcache'])
		|| $_SESSION['slypatch_stcache']['t'] <= 0 || (time() - $_SESSION['slypatch_stcache']['t']) >= 600) {
		$_SESSION['slypatch_stcache'] = array('t' => time(), 'st' => array());
	}
}

/**
 * Overwrite one row with the deterministic outcome of a single-patch action
 * (applyone ok -> applied, restoreone ok -> notapplied). Does NOT touch the
 * sweep timestamp: other rows keep their original freshness window.
 *
 * @param  string $name   Patch short name
 * @param  string $status New status
 * @return void
 */
function slyPatchStatusCacheSet($name, $status)
{
	if (!isset($_SESSION['slypatch_stcache']) || !is_array($_SESSION['slypatch_stcache'])) {
		return;
	}
	$_SESSION['slypatch_stcache']['st'][$name] = array('status' => $status, 'output' => '');
}

/**
 * Drop the whole status cache — after bulk/tree-wide actions (applyall,
 * bundle restores, uploads) every row must be re-measured.
 *
 * @return void
 */
function slyPatchStatusCacheInvalidate()
{
	unset($_SESSION['slypatch_stcache']);
}

/**
 * Parse the list of target files from a unified diff.
 *
 * The sly24.0-*.patch headers are repo-root relative ("+++ b/htdocs/<path>")
 * because gen_sly24_patches.sh diffs from the repository root. Everything
 * downstream of this function (backup paths, packs, bundles, whitelist,
 * upload target list) works with DOL_DOCUMENT_ROOT-relative paths, so a
 * leading "htdocs/" segment is stripped when present. Keep in sync with
 * the engine's -p2 (strips "a/htdocs/") in slyPatchEngine().
 *
 * @param  string $patchfile Absolute path to the .patch file
 * @return array  List of paths relative to DOL_DOCUMENT_ROOT
 */
function slyPatchTargetFiles($patchfile)
{
	$targets = array();
	$fh = fopen($patchfile, 'r');
	if (!$fh) {
		return $targets;
	}
	while (($line = fgets($fh)) !== false) {
		if (preg_match('/^\+\+\+ b\/(.+)$/', rtrim($line, "\r\n"), $m)) {
			$rel = $m[1];
			if (strpos($rel, 'htdocs/') === 0) {
				$rel = substr($rel, strlen('htdocs/'));
			}
			$targets[] = $rel;
		}
	}
	fclose($fh);
	return $targets;
}

/**
 * Apply one patch. Deliberately minimal (user directive 2026-09-23):
 * back up only target files that have no pristine copy yet — never
 * re-backup — then run the engine apply. That's it. Rollback is the
 * per-patch pristine layer (Reset/Restore buttons copy it back), pack
 * creation is first-time-only, and patch QA happens entirely on the
 * development side before deployment — nothing diagnostic runs on the
 * server (user directive 2026-09-23).
 *
 * @param  string $name      Patch short name (whitelisted key)
 * @param  array  $engine    Result of slyPatchEngine()
 * @return array  array('ok'=>bool, 'log'=>string)
 */
function slyPatchApply($name, $engine)
{
	$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.basename($name).'.patch';
	if (!is_readable($patchfile)) {
		return array('ok' => false, 'log' => 'Patch file not found: '.basename($patchfile));
	}

	$targets = slyPatchTargetFiles($patchfile);
	$perPatchDir = DOL_DATA_ROOT.'/slycustom/patch-backups/per-patch/'.basename($name);
	$copiedPerPatch = 0;
	$keptPerPatch = 0;
	foreach ($targets as $rel) {
		$src = DOL_DOCUMENT_ROOT.'/'.$rel;
		if (!is_file($src)) {
			continue; // new file created by the patch, nothing to back up
		}
		$dstPerPatch = $perPatchDir.'/'.$rel;
		if (is_file($dstPerPatch)) {
			$keptPerPatch++; // pristine copy already exists — never re-backup
			continue;
		}
		dol_mkdir(dirname($dstPerPatch));
		if (copy($src, $dstPerPatch)) {
			$copiedPerPatch++;
		}
	}

	// Pack from the pristine per-patch layer, first time only (an existing
	// pack is kept — content is deterministic).
	$packLog = slyPatchMakePack($name, $targets, $perPatchDir);
	$log = $packLog['log'];

	$cmd = 'cd '.escapeshellarg(DOL_DOCUMENT_ROOT).' && '.sprintf($engine['apply'], escapeshellarg(slyPatchNormalizePatchFile($patchfile)));
	exec($cmd, $out, $ret);
	$log .= "\n".($ret === 0 ? 'OK' : 'FAILED (exit '.$ret.')')."\n".implode("\n", $out);
	$log .= "\nPer-patch backup: $perPatchDir ($copiedPerPatch new, $keptPerPatch kept)";

	return array('ok' => ($ret === 0), 'log' => $log);
}

/**
 * Best-effort recursive removal of a staging directory. Used only for the
 * upload-bundle temp dir; failures are silently ignored (the dir lives
 * under documents/ where a leftover is harmless and visible to the admin).
 *
 * @param  string $dir Absolute path to remove
 * @return void
 */
function slyPatchRmDirTree($dir)
{
	if (!is_dir($dir)) {
		return;
	}
	$rii = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ($rii as $f) {
		$f->isDir() ? @rmdir($f->getPathname()) : @unlink($f->getPathname());
	}
	@rmdir($dir);
}

/**
 * Restore every file in a patch's per-patch backup directory back to its
 * original htdocs-relative location. Used by the per-patch Reset button —
 * copies are local (no git, no network) and complete in well under a second.
 *
 * @param  string $name Patch short name (whitelisted key, basename-safe)
 * @return array        array('ok'=>bool, 'log'=>string, 'restored'=>int,
 *                          'missing'=>bool, 'failList'=>array<relPath=>reason>)
 */
function slyPatchRestoreFilesFromBackup($name)
{
	$perPatchDir = DOL_DATA_ROOT.'/slycustom/patch-backups/per-patch/'.basename($name);
	if (!is_dir($perPatchDir)) {
		return array(
			'ok'       => false,
			'log'      => 'No per-patch backup at '.$perPatchDir.' (this patch was never applied, or its backup was deleted).',
			'restored' => 0,
			'missing'  => true,
			'failList' => array(),
		);
	}
	$restored = 0;
	$failList = array();
	$entries = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($perPatchDir, FilesystemIterator::SKIP_DOTS),
		RecursiveIteratorIterator::SELF_FIRST
	);
	foreach ($entries as $info) {
		if ($info->isDir()) {
			continue;
		}
		$rel = substr(str_replace('\\', '/', $info->getPathname()), strlen(str_replace('\\', '/', $perPatchDir)) + 1);
		if ($rel === '' || strpos($rel, '..') !== false) {
			// belt-and-braces: refuse anything that smells like a traversal
			$failList[$rel] = 'unsafe relative path';
			continue;
		}
		$dst = DOL_DOCUMENT_ROOT.'/'.$rel;
		if (!is_dir(dirname($dst))) {
			dol_mkdir(dirname($dst));
		}
		if (@copy($info->getPathname(), $dst)) {
			$restored++;
		} else {
			$failList[$rel] = 'copy failed';
		}
	}
	$lines = array("Restored $restored file(s) from $perPatchDir");
	if ($failList !== array()) {
		$lines[] = 'Failed: '.implode(', ', array_map(function ($k, $v) {
			return "$k ($v)";
		}, array_keys($failList), array_values($failList)));
	}
	return array('ok' => $failList === array(), 'log' => implode("\n", $lines), 'restored' => $restored, 'missing' => false, 'failList' => $failList);
}

/**
 * Extract a .tar.gz archive into $targetDir using the system tar. Returns
 * the list of relative entries (no `..` / no absolute paths) so the caller
 * can whitelist them before doing anything destructive. The archive is NOT
 * deleted by this helper — caller owns the temp file lifecycle.
 *
 * Strict safety net: entries are listed in verbose mode (`tar -tvzf`) so
 * link/device entries are visible and refused BEFORE extraction — a tar
 * symlink followed by a path through it would otherwise escape $targetDir.
 * Every entry must be a relative file path without `..` segments. The
 * tarball is unpacked with `tar -xzf` from inside $targetDir.
 *
 * @param  string $archivePath Absolute path to a .tar.gz file
 * @param  string $targetDir   Absolute path to an existing writable dir
 * @return array  array('ok'=>bool,'log'=>string,'entries'=>array)
 */
function slyPatchExtractTarGz($archivePath, $targetDir)
{
	if (!is_readable($archivePath)) {
		return array('ok' => false, 'log' => 'Archive not readable: '.$archivePath, 'entries' => array());
	}
	if (!is_dir($targetDir)) {
		return array('ok' => false, 'log' => 'Target dir not found: '.$targetDir, 'entries' => array());
	}
	// Enumerate entries first so we can refuse unsafe paths BEFORE extracting.
	// Verbose listing: first field is the mode string, whose type character
	// ('l' = symlink, 'h' = hardlink, block/char device...) we refuse.
	$cmd = 'tar -tvzf '.escapeshellarg($archivePath).' 2>&1';
	exec($cmd, $listOut, $listRet);
	if ($listRet !== 0) {
		return array('ok' => false, 'log' => 'tar -tvzf failed: '.implode("\n", $listOut), 'entries' => array());
	}
	$safe = array();
	foreach ($listOut as $raw) {
		$raw = rtrim($raw, "\r\n");
		if ($raw === '') continue;
		if (!preg_match('/^([-dlhcbp])[rwxstST-]+\s/', $raw, $typeM)) {
			return array('ok' => false, 'log' => 'Archive entry has unparseable type: '.htmlspecialchars($raw, ENT_QUOTES, 'UTF-8'), 'entries' => array());
		}
		if ($typeM[1] !== '-') {
			return array('ok' => false, 'log' => 'Archive contains a non-regular entry (link/device): '.htmlspecialchars($raw, ENT_QUOTES, 'UTF-8'), 'entries' => array());
		}
		// Path = last whitespace-separated token (works with user/group cols).
		$rel = trim(substr($raw, strrpos($raw, ' ')));
		$rel = ltrim($rel, '/');
		if ($rel === '' || strpos($rel, '..') !== false) {
			return array('ok' => false, 'log' => 'Archive contains unsafe path: '.htmlspecialchars($raw, ENT_QUOTES, 'UTF-8'), 'entries' => array());
		}
		$safe[] = $rel;
	}
	$cmd = 'cd '.escapeshellarg($targetDir).' && tar -xzf '.escapeshellarg($archivePath).' 2>&1';
	exec($cmd, $exOut, $exRet);
	if ($exRet !== 0) {
		return array('ok' => false, 'log' => 'tar -xzf failed: '.implode("\n", $exOut), 'entries' => $safe);
	}
	return array('ok' => true, 'log' => 'Extracted '.count($safe).' entries', 'entries' => $safe);
}

/**
 * Build an in-memory reverse map: every htdocs-relative path -> list of
 * patch short names whose `+++ b/<path>` headers mention it. Used by the
 * upload-bundle path to know which per-patch/<name>/ dir each uploaded
 * file belongs to (so the upload not only restores DOL_DOCUMENT_ROOT but
 * also seeds the per-patch backup layer that future Reset calls rely on).
 *
 * @return array<string, array<string>> file => [patch names]
 */
function slyPatchFileToPatchesMap()
{
	global $PATCHES;
	$map = array();
	foreach (array_keys($PATCHES) as $name) {
		$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$name.'.patch';
		if (!is_readable($patchfile)) continue;
		foreach (slyPatchTargetFiles($patchfile) as $rel) {
			if (!is_string($rel) || $rel === '' || strpos($rel, '..') !== false) continue;
			if (!isset($map[$rel])) $map[$rel] = array();
			$map[$rel][] = $name;
		}
	}
	return $map;
}

/**
 * Ingest an operator-uploaded clean 24.0.1 bundle tar.gz into two places:
 *   (a) DOL_DOCUMENT_ROOT  — restore every target file to its pristine
 *       upstream contents (overwrites the dirty tree currently sitting in
 *       htdocs/ — exactly what we need when every patch reports Conflict
 *       because the tree has drifted away from 24.0.1);
 *   (b) documents/slycustom/patch-backups/per-patch/<name>/ — seed a
 *       per-patch backup for every patch that touches the file, so the
 *       next Reset / Restore round can run as a pure local `cp` without
 *       ever needing this upload path again.
 *
 * Whitelist: only files in slyPatchAllTargetFiles() are accepted. Anything
 * else in the archive is silently dropped (a pristine 24.0.1 bundle should
 * not carry anything else, and this protects the operator from typos).
 *
 * Caller responsibility: the archive has already been whitelisted by
 * basename, size-capped, and is on a trusted local temp path. This helper
 * does not move or delete $archivePath.
 *
 * @param  string $archivePath Absolute path to the uploaded .tar.gz
 * @return array  array('ok'=>bool,'log'=>string,'restored'=>int,'seeded'=>array)
 */
function slyPatchIngestUploadedBundle($archivePath)
{
	// Single source of truth: the file->patches reverse map. Its keys are
	// exactly the whitelisted htdocs-relative paths, so we never risk an
	// isset() mismatch between two independently-built whitelists.
	$fileToPatches = slyPatchFileToPatchesMap();
	if ($fileToPatches === array()) {
		return array('ok' => false, 'log' => 'No patch target files known — refusing upload.', 'restored' => 0, 'seeded' => array());
	}
	$tempDir = DOL_DATA_ROOT.'/slycustom/patch-backups/.upload_'.bin2hex(random_bytes(4));
	if (!slyPatchEnsureDir($tempDir)) {
		return array('ok' => false, 'log' => 'Could not create temp dir '.$tempDir, 'restored' => 0, 'seeded' => array());
	}
	$ex = slyPatchExtractTarGz($archivePath, $tempDir);
	if (!$ex['ok']) {
		slyPatchRmDirTree($tempDir);
		return array('ok' => false, 'log' => 'Extraction failed: '.$ex['log'], 'restored' => 0, 'seeded' => array());
	}
	$restored = 0;
	$seeded = array();
	$reseeded = 0;
	$failed = array();
	foreach (array_keys($fileToPatches) as $rel) {
		$src = $tempDir.'/'.$rel;
		if (!is_file($src)) {
			// Tolerate bundles packed from the REPO root (htdocs/<path> layout).
			$alt = $tempDir.'/htdocs/'.$rel;
			if (is_file($alt)) {
				$src = $alt;
			} else {
				// File absent from the uploaded archive — fine, the operator
				// may have packed only a subset; skip silently.
				continue;
			}
		}
		// (a) Restore into DOL_DOCUMENT_ROOT.
		$dst = DOL_DOCUMENT_ROOT.'/'.$rel;
		if (!is_dir(dirname($dst))) {
			dol_mkdir(dirname($dst));
		}
		if (!@copy($src, $dst)) {
			$failed[] = "$rel (copy to DOL_DOCUMENT_ROOT failed)";
			continue;
		}
		$restored++;
		// (b) (Re)seed per-patch backup for every patch that touches this file.
		// The upload is an explicit reset-to-pristine operation (the confirm
		// dialog asserts a clean 24.0.1 source tree), so existing backup files
		// are OVERWRITTEN — a previously poisoned backup layer (e.g. seeded
		// from a non-pristine bundle) is exactly what this must displace.
		foreach (($fileToPatches[$rel] ?? array()) as $name) {
			$perPatchFile = DOL_DATA_ROOT.'/slycustom/patch-backups/per-patch/'.basename($name).'/'.$rel;
			$existed = is_file($perPatchFile);
			if ($existed && !is_writable($perPatchFile)) {
				$failed[] = "$rel (per-patch backup for $name not writable)";
				continue;
			}
			if (!is_dir(dirname($perPatchFile))) {
				dol_mkdir(dirname($perPatchFile));
			}
			if (@copy($src, $perPatchFile)) {
				if ($existed) {
					$reseeded++;
				} else {
					if (!isset($seeded[$name])) $seeded[$name] = 0;
					$seeded[$name]++;
				}
			}
		}
	}
	slyPatchRmDirTree($tempDir);

	$targetTotal = count($fileToPatches);
	$absent = $targetTotal - $restored - count($failed);
	$lines = array();
	$lines[] = "Restored $restored file(s) from uploaded bundle into DOL_DOCUMENT_ROOT";
	$lines[] = "Coverage: $restored/$targetTotal target file(s) present in archive".($absent > 0 ? "; $absent absent (operator may have packed a subset)" : ' — complete');
	if (count($seeded) > 0) {
		$pairs = array();
		foreach ($seeded as $n => $c) $pairs[] = "$n ($c file(s))";
		$lines[] = 'Seeded per-patch backup for '.count($seeded).' patch(es): '.implode(', ', $pairs);
	}
	if ($reseeded > 0) {
		$lines[] = "Re-seeded (overwritten) $reseeded existing per-patch backup file(s) with bundle content";
	}
	if (count($seeded) === 0 && $reseeded === 0) {
		$lines[] = 'No per-patch backup was seeded (no overlap with patch targets)';
	}
	if ($failed !== array()) {
		$lines[] = 'Failures: '.implode('; ', $failed);
	}
	return array(
		'ok' => $failed === array(),
		'log' => implode("\n", $lines),
		'restored' => $restored,
		'seeded' => $seeded,
		'reseeded' => $reseeded,
	);
}

/**
 * Stream the deduped union of every sly24.0-*.patch target file as a
 * plain-text list (one htdocs-relative path per line, no header). Used
 * by the operator to build a clean-24.0.1 bundle offline with:
 *
 *   tar -czf sly24.0-bundle_<ts>.tar.gz -T list.txt
 *
 * on a pristine git clone of Dolibarr 24.0.1, then upload it to recover
 * from a "all patches Conflict + no per-patch backup" deadlock.
 */
function slyPatchDownloadTargetList()
{
	$targets = slyPatchAllTargetFiles();
	header('Content-Type: text/plain');
	header('Content-Disposition: attachment; filename="sly24.0-target-list.txt"');
	header('Cache-Control: no-cache');
	echo implode("\n", $targets);
}

/**
 * Pack every pre-patch target file of one patch into a single tar.gz archive
 * under DOL_DATA_ROOT/slycustom/patch-backups/packs/. Complementary to the
 * per-file per-patch backup: the pack is one portable artifact holding all
 * files a given patch would touch, in pristine (pre-patch) form, so it can
 * be downloaded, archived, or fed back into slyPatchRestoreFromPack on a
 * different host.
 *
 * Pack failure is reported but does NOT fail the surrounding slyPatchApply
 * call — the per-file backup is independent and already covers rollback.
 *
 * @param  string $name    Patch short name (basename-safe whitelist key)
 * @param  array  $targets Pre-patch file list (htdocs-relative paths)
 * @return array  array('ok'=>bool,'log'=>string)
 */
function slyPatchMakePack($name, $targets, $srcRoot = '')
{
	$packDir = DOL_DATA_ROOT.'/slycustom/patch-backups/packs';
	if (!slyPatchEnsureDir($packDir)) {
		return array('ok' => false, 'log' => 'Pack: could not create dir '.$packDir);
	}
	// Deterministic content (pristine files never change): when a pack for
	// this patch already exists, keep it instead of spawning another tar —
	// applyall would otherwise pay 17 tar invocations for nothing.
	$existing = slyPatchListPacks($name);
	if ($existing !== array()) {
		$newest = array_key_first($existing);
		return array('ok' => true, 'log' => 'Pack: existing '.basename($newest).' kept (pristine content is deterministic)');
	}
	if ($srcRoot === '') {
		$srcRoot = DOL_DOCUMENT_ROOT;
	}
	$lines = array();
	foreach ($targets as $rel) {
		$rel = ltrim($rel, '/');
		if ($rel === '' || strpos($rel, '..') !== false) continue;
		if (is_file($srcRoot.'/'.$rel)) {
			$lines[] = $rel;
		}
	}
	if ($lines === array()) {
		return array('ok' => true, 'log' => 'Pack: nothing to pack (patch only creates new files)');
	}
	$listFile = $packDir.'/.list_'.basename($name).'_'.bin2hex(random_bytes(4));
	file_put_contents($listFile, implode("\n", $lines));
	$packFile = $packDir.'/sly24.0-'.basename($name).'_'.dol_print_date(dol_now(), 'dayhourlog').'.tar.gz';
	$cmd = 'cd '.escapeshellarg($srcRoot).' && tar -czf '.escapeshellarg($packFile).' --no-recursion -T '.escapeshellarg($listFile).' 2>&1';
	exec($cmd, $tarOut, $tarRet);
	@unlink($listFile);
	if ($tarRet !== 0) {
		@unlink($packFile);
		return array('ok' => false, 'log' => 'Pack FAILED: '.implode("\n", $tarOut));
	}
	$size = @filesize($packFile);
	return array(
		'ok' => true,
		'log' => 'Pack: '.$packFile.' ('.($size !== false ? $size : '?').' bytes, '.count($lines).' file(s))'
	);
}

/**
 * List every pack archive present for a given patch, newest first.
 *
 * @param  string $name Patch short name
 * @return array  Map: filename => filemtime (unix seconds), newest first
 */
function slyPatchListPacks($name)
{
	$packDir = DOL_DATA_ROOT.'/slycustom/patch-backups/packs';
	$out = array();
	if (!is_dir($packDir)) return $out;
	$prefix = 'sly24.0-'.basename($name).'_';
	$suffix = '.tar.gz';
	$dh = @opendir($packDir);
	if ($dh === false) return $out;
	while (($f = readdir($dh)) !== false) {
		if (substr($f, 0, strlen($prefix)) === $prefix && substr($f, -strlen($suffix)) === $suffix) {
			$full = $packDir.'/'.$f;
			if (is_file($full)) {
				$out[$f] = filemtime($full);
			}
		}
	}
	closedir($dh);
	arsort($out);
	return $out;
}

/**
 * Restore every file in one pack archive back into DOL_DOCUMENT_ROOT.
 * Security model identical to the upload path: (1) basename restricted to
 * sly24.0-<name>_<ts>.tar.gz, (2) verbose listing parsed to refuse symlink
 * / hardlink / device entries, (3) traversal check, (4) every entry must be
 * in the union of all patch target files — an archive planted in packs/
 * cannot touch anything outside the patch tool's own blast radius.
 *
 * @param  string $packFilename Basename only; whitelist regex restricts
 *                              it to sly24.0-<name>_<ts>.tar.gz
 * @return array  array('ok'=>bool,'log'=>string)
 */
function slyPatchRestoreFromPack($packFilename)
{
	$packFilename = basename($packFilename);
	if (!preg_match('/^sly24\.0-[a-zA-Z0-9_.-]+\.tar\.gz$/', $packFilename)) {
		return array('ok' => false, 'log' => 'Refused: pack name format mismatch: '.htmlspecialchars($packFilename));
	}
	$full = DOL_DATA_ROOT.'/slycustom/patch-backups/packs/'.$packFilename;
	if (!is_readable($full)) {
		return array('ok' => false, 'log' => 'Pack not found: '.$packFilename);
	}
	// Verbose listing: type character first on each line ('-' = regular
	// file; 'l'/'h' links and devices are refused before any extraction).
	$listCmd = 'tar -tvzf '.escapeshellarg($full).' 2>&1';
	exec($listCmd, $listOut, $listRet);
	if ($listRet !== 0) {
		return array('ok' => false, 'log' => 'tar list failed: '.implode("\n", $listOut));
	}
	$whitelist = array_flip(slyPatchAllTargetFiles());
	$fileCount = 0;
	foreach ($listOut as $entry) {
		$entry = rtrim($entry, "\r\n");
		if ($entry === '') continue;
		if (!preg_match('/^([-dlhcbp])[rwxstST-]+\s/', $entry, $typeM)) {
			return array('ok' => false, 'log' => 'Refused: unparseable archive entry: '.htmlspecialchars($entry));
		}
		if ($typeM[1] !== '-') {
			return array('ok' => false, 'log' => 'Refused: archive contains a non-regular entry (link/device): '.htmlspecialchars($entry));
		}
		$rel = ltrim(trim(substr($entry, strrpos($entry, ' '))), '/');
		if ($rel === '' || substr($rel, -1) === '/') continue;
		if (strpos($rel, '..') !== false) {
			return array('ok' => false, 'log' => 'Refused: archive contains path-traversal entry: '.htmlspecialchars($entry));
		}
		if (!isset($whitelist[$rel])) {
			return array('ok' => false, 'log' => 'Refused: archive entry outside the patch-target whitelist: '.htmlspecialchars($rel));
		}
		$fileCount++;
	}
	if ($fileCount === 0) {
		return array('ok' => true, 'log' => 'Pack is empty (no files to restore)');
	}
	$cmd = 'cd '.escapeshellarg(DOL_DOCUMENT_ROOT).' && tar -xzf '.escapeshellarg($full).' 2>&1';
	exec($cmd, $out, $ret);
	return array(
		'ok' => $ret === 0,
		'log' => 'Extracted '.$fileCount." file(s) from $packFilename to DOL_DOCUMENT_ROOT\n".implode("\n", $out)
	);
}

/**
 * Union the file targets (htdocs-relative) of every patch in the series.
 * Used to build the cross-patch bundle. When two patches touch the same
 * htdocs-relative path (e.g. core + remx + other-modules all edit
 * htdocs/main.inc.php), the union collapses the overlap so the bundle
 * captures each file exactly once.
 *
 * @return array Sorted list of htdocs-relative paths, deduped.
 */
function slyPatchAllTargetFiles()
{
	global $PATCHES;
	$all = array();
	foreach (array_keys($PATCHES) as $name) {
		$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$name.'.patch';
		if (!is_readable($patchfile)) continue;
		foreach (slyPatchTargetFiles($patchfile) as $f) {
			if (is_string($f) && $f !== '' && strpos($f, '..') === false) {
				$all[$f] = true;
			}
		}
	}
	ksort($all);
	return array_keys($all);
}

/**
 * Pack every file across ALL sly24.0-*.patch target paths (deduped) into
 * a SINGLE tar.gz. The bundle is the safe rollback when per-patch packs
 * would be wrong: when two patches touch the same file, each per-patch
 * pack captures the post-prior-patch state — but the union bundle gives
 * one consistent snapshot captured BEFORE the applyall chain begins.
 *
 * Auto-invoked at the start of every applyall; manually triggerable via
 * action=bundle_create. Older bundles are kept (manual GC is the
 * operator's call — we never delete backups automatically).
 *
 * @return array array('ok'=>bool,'log'=>string,'packfile'=>string,'count'=>int)
 */
function slyPatchMakeBundle()
{
	$targets = slyPatchAllTargetFiles();
	if ($targets === array()) {
		return array('ok' => true, 'log' => 'Bundle: union of all patch targets is empty', 'packfile' => '', 'count' => 0);
	}
	$packDir = DOL_DATA_ROOT.'/slycustom/patch-backups/packs';
	if (!slyPatchEnsureDir($packDir)) {
		return array('ok' => false, 'log' => 'Bundle: could not create dir '.$packDir, 'packfile' => '', 'count' => 0);
	}
	$lines = array();
	foreach ($targets as $rel) {
		$rel = ltrim($rel, '/');
		if ($rel === '' || strpos($rel, '..') !== false) continue;
		if (is_file(DOL_DOCUMENT_ROOT.'/'.$rel)) {
			$lines[] = $rel;
		}
	}
	if ($lines === array()) {
		return array('ok' => true, 'log' => 'Bundle: every unioned target is a new file (nothing to pack)', 'packfile' => '', 'count' => 0);
	}
	$listFile = $packDir.'/.list_bundle_'.bin2hex(random_bytes(4));
	file_put_contents($listFile, implode("\n", $lines));
	$packFile = $packDir.'/sly24.0-bundle_'.dol_print_date(dol_now(), 'dayhourlog').'.tar.gz';
	$cmd = 'cd '.escapeshellarg(DOL_DOCUMENT_ROOT).' && tar -czf '.escapeshellarg($packFile).' --no-recursion -T '.escapeshellarg($listFile).' 2>&1';
	exec($cmd, $tarOut, $tarRet);
	@unlink($listFile);
	if ($tarRet !== 0) {
		@unlink($packFile);
		return array('ok' => false, 'log' => 'Bundle FAILED: '.implode("\n", $tarOut), 'packfile' => '', 'count' => count($lines));
	}
	$size = @filesize($packFile);
	return array(
		'ok' => true,
		'log' => 'Bundle: '.$packFile.' ('.($size !== false ? $size : '?').' bytes, '.count($lines).' file(s))',
		'packfile' => $packFile,
		'count' => count($lines)
	);
}

/**
 * Return the basename + mtime of the latest existing bundle on disk.
 *
 * @return array array(basename|'', mtime|0)
 */
function slyPatchLatestBundle()
{
	$packDir = DOL_DATA_ROOT.'/slycustom/patch-backups/packs';
	if (!is_dir($packDir)) return array('', 0);
	$candidates = array();
	$dh = @opendir($packDir);
	if ($dh === false) return array('', 0);
	while (($f = readdir($dh)) !== false) {
		if (strpos($f, 'sly24.0-bundle_') === 0 && substr($f, -7) === '.tar.gz') {
			$full = $packDir.'/'.$f;
			if (is_file($full)) {
				$candidates[$f] = filemtime($full);
			}
		}
	}
	closedir($dh);
	if (empty($candidates)) return array('', 0);
	arsort($candidates);
	$first = array_key_first($candidates);
	return array($first, $candidates[$first]);
}

// --- Actions ---
$action = GETPOST('action', 'aZ09');
// Keep the raw name (hyphens matter) and validate strictly against the whitelist below.
$applyname = GETPOST('name', 'alpha');
$logs = array();
$error = 0;

// Stream a pack archive as a binary download. GET-only (no state change);
// one-shot link usable from a browser address bar. Token is checked against
// the session newtoken. Exits immediately — no UI is rendered after this.
if ($action == 'downloadpack') {
	$pack = basename(GETPOST('pack', 'filename'));
	$token = GETPOST('token', 'aZ09');
	if (!preg_match('/^sly24\.0-[a-zA-Z0-9_.-]+\.tar\.gz$/', $pack) || empty($_SESSION['newtoken']) || $token !== $_SESSION['newtoken']) {
		accessforbidden();
		exit;
	}
	$full = DOL_DATA_ROOT.'/slycustom/patch-backups/packs/'.$pack;
	if (!is_readable($full)) {
		accessforbidden();
		exit;
	}
	header('Content-Type: application/gzip');
	header('Content-Disposition: attachment; filename="'.$pack.'"');
	header('Content-Length: '.filesize($full));
	header('Cache-Control: no-cache');
	readfile($full);
	exit;
}

// Stream the union of every sly24.0-*.patch target path as a one-path-per-
// line text file. Operator downloads it on a clean 24.0.1 git clone to build
// a pristine bundle tar.gz locally, then uploads that tar.gz via the
// upload_bundle action. Token-gated to mirror downloadpack.
if ($action == 'downloadtargetlist') {
	$token = GETPOST('token', 'aZ09');
	if (empty($_SESSION['newtoken']) || $token !== $_SESSION['newtoken']) {
		accessforbidden();
		exit;
	}
	slyPatchDownloadTargetList();
	exit;
}

if (in_array($action, array('applyall', 'applyone', 'restoreone', 'resetone', 'resetapplyall_smart', 'restorefrompack', 'bundle_create', 'restore_bundle', 'upload_bundle')) && $versionOk) {
	// main.inc.php rejects a wrong token automatically; a missing one on POST we reject here.
	if ($_SERVER['REQUEST_METHOD'] == 'POST' && !GETPOSTISSET('token')) {
		accessforbidden();
		exit;
	}
	$engine = slyPatchEngine();

	// Local-only reset path: triggered when one or more patches report
	// "Conflict". We restore the conflict-touched files using each patch's
	// own per-patch backup (a pristine pre-patch copy of every file that
	// patch touched, captured the first time slyPatchApply ran). No git,
	// no network, no archive upload — only local files under
	// documents/slycustom/patch-backups/per-patch/<name>/. Every other
	// file in DOL_DOCUMENT_ROOT stays untouched, so this is safe to run
	// on a partially-customised deployment.
	//
	// On success, falls through to the apply-all chain so the freshly
	// re-baselined tree ends with all SLY customisations reapplied.
	if ($action == 'resetapplyall_smart') {
		// Fresh sweep: the conflict set decides which backups get restored.
		slyPatchStatusSweepBegin();
		$conflictPatches = array();
		foreach ($PATCHES as $name => $_) {
			$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$name.'.patch';
			$st = slyPatchStatusCached($name, $patchfile, $engine);
			if ($st['status'] == 'conflict') {
				$conflictPatches[] = $name;
			}
		}

		if ($conflictPatches === array()) {
			$logs[] = '── Smart reset: no conflict patches detected; falling through to plain apply-all.';
		} else {
			$logs[] = '── Conflict patches: '.implode(', ', $conflictPatches);
			$logs[] = '── Source: per-patch backup (documents/slycustom/patch-backups/per-patch/<name>/) — pure local cp, no network / no git.';
			$smartOk = true;
			$missing = array();
			foreach ($conflictPatches as $name) {
				$r = slyPatchRestoreFilesFromBackup($name);
				$logs[] = '──   '.$name.': '.($r['ok'] ? 'OK ('.$r['restored'].' file(s))' : 'FAILED')."\n".$r['log'];
				if (!$r['ok']) {
					$smartOk = false;
					if (!empty($r['missing'])) {
						$missing[] = $name;
					}
				}
			}
			if (!$smartOk) {
				if ($missing !== array()) {
					setEventMessages($langs->trans('SlyPatchResetLocalFailed', implode(', ', $missing)), null, 'errors');
				} else {
					setEventMessages($langs->trans('SlyPatchResetAllFailed'), null, 'errors');
				}
				header('Location: '.$_SERVER['PHP_SELF'].'?message='.urlencode('PatchApplyError'));
				exit;
			}
		}
		// Walk the 17-patch chain over the freshly re-baselined tree. The
		// restores above changed files — the sweep rows are stale now.
		slyPatchStatusCacheInvalidate();
		$action = 'applyall';
	}

	if ($action == 'applyone') {
		if (!array_key_exists($applyname, $PATCHES)) {
			accessforbidden();
			exit;
		}
		// Force a live measurement for the apply decision: cached rows can be
		// minutes old and the operator may have changed files out-of-band.
		$st = slyPatchStatusCached($applyname, DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$applyname.'.patch', $engine, true);
		if ($st['status'] == 'notapplied') {
			$r = slyPatchApply($applyname, $engine);
			$logs[] = '── sly24.0-'.$applyname.'.patch: '.($r['ok'] ? 'applied' : 'FAILED')."\n".$r['log'];
			if ($r['ok']) {
				slyPatchStatusCacheSet($applyname, 'applied');
			} else {
				$error++;
			}
		} else {
			$logs[] = '── sly24.0-'.$applyname.'.patch: skipped (status: '.$st['status'].')';
		}
	}

	if ($action == 'restoreone') {
		// Roll back a single patch: copy every per-patch backup file back to its
		// htdocs-relative location and stop there (no re-apply). After this the
		// patch is in the "not applied" state — the file tree matches the
		// pre-patch contents, so a forward `git apply --check` succeeds.
		if (!array_key_exists($applyname, $PATCHES)) {
			accessforbidden();
			exit;
		}
		$r = slyPatchRestoreFilesFromBackup($applyname);
		$logs[] = '── sly24.0-'.$applyname.'.patch: restore from backup '.($r['ok'] ? 'OK' : 'FAILED')."\n".$r['log'];
		if ($r['ok']) {
			slyPatchStatusCacheSet($applyname, 'notapplied');
		} else {
			$error++;
		}
	}

	if ($action == 'resetone') {
		// Per-patch Reset: copy the patch's pre-patch backup back to
		// DOL_DOCUMENT_ROOT, then re-apply the patch so the row lands
		// back on the "applied" badge (matching what a fresh install
		// would look like). The per-patch backup is captured the first
		// time slyPatchApply runs and never overwritten afterwards, so
		// a Reset is always a local `cp` away — no git, no network,
		// no archive.
		//
		// If the per-patch backup is missing (the patch was applied by
		// an older slycustom release that didn't have this backup layer,
		// or the backup was wiped), Reset refuses with a clear recovery
		// message instead of falling back to git / auto-download — the
		// tool's only rollback source is the local pre-backup.
		if (!array_key_exists($applyname, $PATCHES)) {
			accessforbidden();
			exit;
		}
		$r = slyPatchRestoreFilesFromBackup($applyname);
		$logs[] = '── sly24.0-'.$applyname.'.patch: restore from per-patch backup '.($r['ok'] ? 'OK' : 'FAILED').' ('.$r['restored'].' file(s)'.")\n".$r['log'];
		if (!$r['ok']) {
			if (!empty($r['missing'])) {
				setEventMessages($langs->trans('SlyPatchResetLocalFailed', $applyname), null, 'errors');
			}
			$error++;
		}
		// Re-apply so the row lands on the "applied" badge (post-restore the
		// file tree is in pre-patch state; forward `git apply` brings it back
		// to the patched state, which is the operator's intent).
		$st2 = slyPatchStatus(DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$applyname.'.patch', $engine);
		if ($st2['status'] == 'notapplied') {
			$ra = slyPatchApply($applyname, $engine);
			$logs[] = '── sly24.0-'.$applyname.'.patch: re-apply '.($ra['ok'] ? 'OK' : 'FAILED')."\n".$ra['log'];
			if (!$ra['ok']) {
				$error++;
			}
		} else {
			$logs[] = '── sly24.0-'.$applyname.'.patch: re-apply skipped (status: '.$st2['status'].')';
		}
		// Branchy outcomes (restore ok / re-apply ok / skipped) — drop the
		// cache and let the next view re-measure instead of guessing.
		slyPatchStatusCacheInvalidate();
	}

	if ($action == 'applyall') {
		// Pre-applyall snapshot: bundle (every patch target, deduped) into
		// one tar.gz so the operator can one-shot roll back the entire
		// patch family, regardless of how many patches overlap on the
		// same file. Failure here is logged but does NOT block the applyall
		// chain — the per-patch packs below remain the source of truth.
		$bundleLog = slyPatchMakeBundle();
		$logs[] = '── Pre-applyall bundle: '.($bundleLog['ok'] ? 'OK' : 'FAILED')."\n".$bundleLog['log'];

		// One shared sweep for the whole chain (17 patches × 2 dry-runs would
		// otherwise be paid again by the post-redirect view).
		slyPatchStatusSweepBegin();
		foreach (array_keys($PATCHES) as $name) {
			$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$name.'.patch';
			$st = slyPatchStatusCached($name, $patchfile, $engine);
			if ($st['status'] == 'notapplied') {
				$r = slyPatchApply($name, $engine);
				$logs[] = '── sly24.0-'.$name.'.patch: '.($r['ok'] ? 'applied' : 'FAILED')."\n".$r['log'];
				if ($r['ok']) {
					slyPatchStatusCacheSet($name, 'applied');
				} else {
					$error++;
					break; // stop the chain on first failure: later patches may depend on it
				}
			} else {
				$logs[] = '── sly24.0-'.$name.'.patch: skipped (status: '.$st['status'].')';
			}
		}
	}

	if ($action == 'restorefrompack') {
		// Roll back a single patch by re-extracting its latest pack tar.gz.
		// Same end-state as the per-row Restore button (the row lands on
		// "not applied") — just sourced from one archive instead of
		// scattered files. Useful for cross-env rollback: download a pack
		// from prod, upload it to d-test, restore with one click.
		$pack = basename(GETPOST('pack', 'filename'));
		if (!preg_match('/^sly24\.0-[a-zA-Z0-9_.-]+\.tar\.gz$/', $pack)) {
			$logs[] = '── restorefrompack: refused pack name '.htmlspecialchars($pack);
			$error++;
		} else {
			slyPatchStatusCacheInvalidate();
			$r = slyPatchRestoreFromPack($pack);
			$logs[] = '── restorefrompack '.htmlspecialchars($pack).': '.($r['ok'] ? 'OK' : 'FAILED')."\n".$r['log'];
			if (!$r['ok']) {
				$error++;
			}
		}
	}

	if ($action == 'bundle_create') {
		// Manually snapshot the union of all patch targets — independent
		// from applyall. Useful before risky drift edits or just before
		// a doc walkthrough that needs a guaranteed restore point.
		$r = slyPatchMakeBundle();
		$logs[] = '── create bundle: '.($r['ok'] ? 'OK' : 'FAILED')."\n".$r['log'];
		if (!$r['ok']) {
			$error++;
		}
	}

	if ($action == 'restore_bundle') {
		// One-tar.gz rollback to the pre-applyall state captured by the
		// most recent bundle. Resolves cross-patch overlap: per-patch
		// restore would yield the wrong intermediate state for files
		// touched by more than one patch.
		list($latestBundle, $latestBundleTs) = slyPatchLatestBundle();
		if ($latestBundle === '') {
			$logs[] = '── restore_bundle: no bundle archive exists yet (run applyall once or click Create bundle).';
			$error++;
		} else {
			slyPatchStatusCacheInvalidate();
			$r = slyPatchRestoreFromPack($latestBundle);
			$logs[] = '── restore_bundle '.htmlspecialchars($latestBundle).': '.($r['ok'] ? 'OK' : 'FAILED')."\n".$r['log'];
			if (!$r['ok']) {
				$error++;
			}
		}
	}

	if ($action == 'upload_bundle') {
		// Recovery path for the deadlock where every patch is in Conflict
		// AND the per-patch backup layer is missing (applied by an older
		// slycustom release that lacked this layer, or backups were wiped).
		// The operator builds a clean 24.0.1 tar.gz off-host from a pristine
		// git clone + the target-list downloaded via downloadtargetlist,
		// then uploads it here. The tool whitelists by basename + size,
		// extracts to a temp dir, copies each file into DOL_DOCUMENT_ROOT,
		// and seeds the per-patch backup layer so future Reset calls are a
		// pure local `cp` away. No network, no git — the operator is the
		// only source of bytes, exactly as for every other rollback path.
		//
		// Size cap is 16MB: real bundles are 5-10MB, and a cap at the
		// post_max_size limit (32M on d-test) would be rejected by PHP at
		// the protocol layer with $_FILES empty — a misleading "no file"
		// error instead of our own clear message.
		$uploadErr = '';
		$uploadName = '';
		if (!isset($_FILES['bundle'])) {
			$uploadErr = 'no file in upload field';
		} elseif (!is_array($_FILES['bundle']) || !isset($_FILES['bundle']['error'])) {
			$uploadErr = 'malformed upload payload';
		} elseif ($_FILES['bundle']['error'] !== UPLOAD_ERR_OK) {
			$uploadErr = 'upload error code '.(int) $_FILES['bundle']['error'];
		} else {
			$uploadName = basename((string) $_FILES['bundle']['name']);
			$uploadSize = (int) $_FILES['bundle']['size'];
			if ($uploadSize <= 0 || $uploadSize > 16 * 1024 * 1024) {
				$uploadErr = 'size out of range (1..16MB)';
			} elseif (!preg_match('/^sly24\.0-[a-zA-Z0-9_.-]+\.tar\.gz$/', $uploadName)) {
				$uploadErr = 'basename not whitelisted: '.$uploadName;
			} else {
				$tmp = (string) $_FILES['bundle']['tmp_name'];
				if (!is_readable($tmp)) {
					$uploadErr = 'temp file not readable';
				} else {
					$r = slyPatchIngestUploadedBundle($tmp);
					$logs[] = '── upload_bundle '.htmlspecialchars($uploadName).': '.($r['ok'] ? 'OK' : 'FAILED')."\n".$r['log'];
					if ($r['ok']) {
						slyPatchStatusCacheInvalidate();
						if (!empty($r['reseeded'])) {
							setEventMessages($langs->trans('SlyPatchUploadBundleOkReseeded', (string) $r['restored'], (string) $r['reseeded']), null);
						} else {
							setEventMessages($langs->trans('SlyPatchUploadBundleOk', $r['restored'], count($r['seeded'])), null);
						}
					} else {
						setEventMessages($langs->trans('SlyPatchUploadBundleFailed', $r['log']), null, 'errors');
						$error++;
					}
				}
			}
		}
		if ($uploadErr !== '') {
			setEventMessages($langs->trans('SlyPatchUploadBundleFailed', $uploadErr), null, 'errors');
			$logs[] = '── upload_bundle refused: '.htmlspecialchars($uploadErr);
			$error++;
		}
	}

	// Persist the detailed engine log across the redirect below so the
	// operator actually sees per-patch results, backup paths and failure
	// output (setEventMessages only carries the short banner).
	if ($logs !== array()) {
		$_SESSION['slypatch_lastlogs'] = implode("\n\n", $logs);
	}

	// Same-page redirect pattern to clear the action from the URL.
	header('Location: '.$_SERVER['PHP_SELF'].($error ? '?message='.urlencode('PatchApplyError') : '?message='.urlencode('PatchApplyDone')));
	exit;
}

// --- View ---
llxHeader('', $langs->trans('SlyPatchTool'));

$engine = slyPatchEngine();
$engineAvailable = (trim((string) shell_exec('command -v git 2>/dev/null')) !== '' || trim((string) shell_exec('command -v patch 2>/dev/null')) !== '');

print load_fiche_titre($langs->trans('SlyPatchTool'), '', 'slycustom@slycustom');

// Pack + Bundle layer summary. Per-patch packs are tar.gz one per
// patch. The bundle is the cross-patch one-tar.gz snapshot for
// one-click rollback of the whole patch family (built automatically
// at the start of every applyall; manually triggerable too).
$packDir = DOL_DATA_ROOT.'/slycustom/patch-backups/packs';
$perPatchCount = 0;
$perPatchTotal = 0;
$bundleFiles = array();
if (is_dir($packDir)) {
	foreach (glob($packDir.'/sly24.0-*.tar.gz') ?: array() as $pf) {
		$bn = basename($pf);
		if (strpos($bn, 'sly24.0-bundle_') === 0) {
			$bundleFiles[$pf] = filemtime($pf);
		} else {
			$perPatchCount++;
			$perPatchTotal += (int) @filesize($pf);
		}
	}
}
arsort($bundleFiles);
$latestBundle = !empty($bundleFiles) ? basename(array_key_first($bundleFiles)) : '';
$latestBundleTs = !empty($bundleFiles) ? max($bundleFiles) : 0;
if ($perPatchCount > 0 || $latestBundle !== '') {
	$banner = '';
	if ($perPatchCount > 0) {
		$banner .= $langs->trans('SlyPatchPacksSummary', $perPatchCount, (int) round($perPatchTotal / 1024)).'<br>';
	}
	if ($latestBundle !== '') {
		$banner .= $langs->trans('SlyPatchBundleLatest', $latestBundle, dol_print_date($latestBundleTs, 'dayhour'));
	} else {
		$banner .= $langs->trans('SlyPatchBundleNone');
	}
	print '<div class="info" style="padding:8px;margin:6px 0">'.$banner.'</div>';
}

if (GETPOST('message', 'alpha') == 'PatchApplyDone') {
	setEventMessages($langs->trans('PatchApplyDoneMsg'), null);
}
if (GETPOST('message', 'alpha') == 'PatchApplyError') {
	setEventMessages($langs->trans('PatchApplyErrorMsg'), null, 'errors');
}

print '<div class="fichecenter">';

if (!$versionOk) {
	print '<div class="error" style="padding:8px">'.$langs->trans('SlyPatchVersionWarning', DOL_VERSION).'</div>';
} elseif (!$engineAvailable) {
	print '<div class="error" style="padding:8px">'.$langs->trans('SlyPatchNoEngine').'</div>';
}

// Detailed engine log of the previous POST, persisted through the redirect
// by the action handler. Shown once then discarded.
$savedLogs = '';
if (isset($_SESSION['slypatch_lastlogs'])) {
	$savedLogs = (string) $_SESSION['slypatch_lastlogs'];
	unset($_SESSION['slypatch_lastlogs']);
}
if ($savedLogs !== '') {
	print '<div class="slypatchlog" style="background:#222;color:#dfe;font-family:monospace;font-size:12px;padding:10px;margin:8px 0;white-space:pre-wrap;border-radius:4px">';
	print htmlspecialchars($savedLogs, ENT_QUOTES, 'UTF-8');
	print '</div>';
}

print $langs->trans('SlyPatchToolIntro', $engine['engine']).' · Dolibarr <strong>'.DOL_VERSION.'</strong>'.(version_compare(DOL_VERSION, '24.0.1', '==') ? '' : ' <span class="warning">('.($versionOk ? 'not 24.0.1 — patches are generated against the 24.0.1 baseline' : 'unsupported').'</span>').'<br><br>';

$i = 0;
$nbNotApplied = 0;
$nbConflict = 0;
$nbApplied = 0;
// Initialised BEFORE the loop: the upload/reset cards below test them with
// !== array() and count() — an uninitialised variable on a "conflict but
// backup exists" tree is a PHP 8 TypeError (count(null)) that fatals the
// whole page.
$conflictPatchesList = array();
$missingPerPatchList = array();
// First non-empty engine output among conflict rows — surfaced above the
// table so the operator sees the real git/patch error without hovering.
$conflictSampleName = '';
$conflictSampleOutput = '';
// Buffered <tr> rows — printed after the conflict diagnostic box.
$tableRows = array();
// Status sweep: reuse the session cache inside its 10-minute window — a
// full sweep costs 34 process spawns (2 git dry-runs × 17 patches) per
// PAGE VIEW, which throttled the d-test2 shared host to near-unavailability.
// ?rescan=1 (the Rescan button) forces a fresh sweep.
$forceScan = (GETPOST('rescan', 'int') ? true : false);
slyPatchStatusSweepBegin();
if ($forceScan) {
	$_SESSION['slypatch_stcache']['st'] = array();
}
foreach ($PATCHES as $name => $desckey) {
	// Buffer this row: the conflict diagnostic box collected inside the
	// loop must be printed BEFORE the table opens.
	ob_start();
	$patchfile = DOL_DOCUMENT_ROOT.'/custom/slycustom/patches/sly24.0-'.$name.'.patch';
	$st = array('status' => 'missing', 'output' => '');
	if ($engineAvailable && $versionOk) {
		$st = slyPatchStatusCached($name, $patchfile, $engine, $forceScan);
	}
	if ($st['status'] == 'notapplied') {
		$nbNotApplied++;
	} elseif ($st['status'] == 'conflict') {
		$nbConflict++;
		$conflictPatchesList[] = $name;
		if ($conflictSampleOutput === '' && trim((string) $st['output']) !== '') {
			$conflictSampleName = $name;
			$conflictSampleOutput = (string) $st['output'];
		}
	} elseif ($st['status'] == 'applied') {
		$nbApplied++;
	}
	$perPatchDir = DOL_DATA_ROOT.'/slycustom/patch-backups/per-patch/'.$name;
	$hasPerPatchBackup = is_dir($perPatchDir);
	if ($st['status'] == 'conflict' && !$hasPerPatchBackup) {
		$missingPerPatchList[] = $name;
	}

	print '<tr class="oddeven">';
	print '<td>'.(++$i).'</td>';
	print '<td>sly24.0-'.dol_escape_htmltag($name).'.patch'.(is_readable($patchfile) ? '' : ' <span class="error">('.$langs->trans('FileNotFound').')</span>').'</td>';
	print '<td>'.$langs->trans($desckey).'</td>';
	$badge = '';
	switch ($st['status']) {
		case 'applied':
			$badge = '<span class="badge badge-status4 badge-status" style="color:#1d9f6a">'.$langs->trans('PatchApplied').'</span>';
			break;
		case 'notapplied':
			$badge = '<span class="badge" style="color:#bbb">'.$langs->trans('PatchNotApplied').'</span>';
			break;
		case 'missing':
			$badge = '<span class="badge badge-status8 badge-status">'.$langs->trans('FileNotFound').'</span>';
			break;
		default:
			$badge = '<span class="badge badge-status8 badge-status" title="'.dol_escape_htmltag($st['output']).'">'.$langs->trans('PatchConflict').'</span>';
			break;
	}
	print '<td class="center">'.$badge.'</td>';

	// Per-row action buttons. Each row gets its own self-contained form so the
	// POST body carries only this patch's `name`. Visibility follows the live
	// status:
	//   * Apply   — visible when status=notapplied. Clean forward apply.
	//   * Reset   — visible when status=conflict. Copies the per-patch backup
	//               back into place and re-applies so the row lands back on
	//               "applied". Refuses if no per-patch backup exists yet —
	//               the only rollback source is the local pre-backup.
	//   * Restore — visible when status=applied (and a backup exists). Copies
	//               the per-patch backup back and stops; row becomes
	//               "not applied".
	// status=missing hides every action (the patch file itself is gone).
	print '<td class="right" style="white-space:nowrap">';
	if ($st['status'] == 'notapplied' && $versionOk && $engineAvailable) {
		print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" style="display:inline" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchApplyOneConfirmText', 'sly24.0-'.$name.'.patch')).'\');">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="action" value="applyone">';
		print '<input type="hidden" name="name" value="'.dol_escape_htmltag($name).'">';
		print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchApplyOne').'">';
		print '</form> ';
	}
	if ($st['status'] == 'conflict' && $versionOk && $engineAvailable) {
		print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" style="display:inline" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchResetOneConfirmText', 'sly24.0-'.$name.'.patch')).'\');">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="action" value="resetone">';
		print '<input type="hidden" name="name" value="'.dol_escape_htmltag($name).'">';
		print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchResetOne').'">';
		print '</form> ';
	}
	if ($st['status'] == 'applied' && $hasPerPatchBackup && $versionOk && $engineAvailable) {
		print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" style="display:inline" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchRestoreOneConfirmText', 'sly24.0-'.$name.'.patch')).'\');">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="action" value="restoreone">';
		print '<input type="hidden" name="name" value="'.dol_escape_htmltag($name).'">';
		print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchRestoreOne').'">';
		print '</form> ';
	}

	// Pack-related row buttons — only when at least one pack archive exists
	// on disk for this patch. "Restore from pack" is functionally equivalent
	// to the per-row Restore button above (both leave the row on "not
	// applied"); just sourced from a single tar.gz — useful when migrating
	// a backup across hosts or after a manual pack upload.
	$packsForName = slyPatchListPacks($name);
	$latestPack = '';
	$latestPackTs = 0;
	foreach ($packsForName as $f => $ts) {
		$latestPack = $f;
		$latestPackTs = $ts;
		break;
	}
	if ($latestPack !== '' && $versionOk && $engineAvailable) {
		print ' <a class="butAction" href="'.$_SERVER['PHP_SELF'].'?action=downloadpack&pack='.urlencode($latestPack).'&token='.newToken().'" title="'.dol_escape_htmltag($latestPack).' ('.dol_print_date($latestPackTs, 'dayhour').')">'.$langs->trans('SlyPatchDownloadPack').'</a>';
	}
	if ($latestPack !== '' && ($st['status'] == 'applied' || $st['status'] == 'conflict') && $versionOk && $engineAvailable) {
		print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" style="display:inline" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchRestoreFromPackConfirmText', $latestPack, $latestPack)).'\');">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="action" value="restorefrompack">';
		print '<input type="hidden" name="pack" value="'.dol_escape_htmltag($latestPack).'">';
		print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchRestoreFromPack').'">';
		print '</form> ';
	}
	print '</td>';
	print '</tr>';
	$tableRows[] = ob_get_clean();
}

// Conflict diagnostic: show the engine's own error output (git / patch
// stderr) for the first conflicting patch. Without this the only clue was
// a hover tooltip on the badge — which is how the CRLF and dubious-
// ownership root causes stayed invisible for two debugging rounds.
if ($nbConflict > 0 && $conflictSampleOutput !== '') {
	print '<div class="error" style="padding:8px;margin:8px 0">';
	print $langs->trans('SlyPatchConflictDiagIntro', 'sly24.0-'.$conflictSampleName.'.patch');
	print '<div style="background:#222;color:#dfe;font-family:monospace;font-size:12px;padding:8px;margin-top:6px;white-space:pre-wrap;border-radius:3px;max-height:220px;overflow:auto">';
	$diagLines = explode("\n", $conflictSampleOutput);
	if (count($diagLines) > 25) {
		$diagLines = array_slice($diagLines, 0, 25);
		$diagLines[] = '... ('.(count(explode("\n", $conflictSampleOutput)) - 25).' more line(s))';
	}
	print htmlspecialchars(implode("\n", $diagLines), ENT_QUOTES, 'UTF-8');
	print '</div>';
	print '</div>';
}

print '<table class="noborder centpercent">';
print '<tr class="liste_titre">';
print '<td>#</td>';
print '<td>'.$langs->trans('PatchFile').'</td>';
print '<td>'.$langs->trans('Description').'</td>';
print '<td class="center">'.$langs->trans('Status').'</td>';
print '<td class="right">'.$langs->trans('SlyPatchActions').'</td>';
print '</tr>';
print implode('', $tableRows);
print '</table>';

print '<div class="opacitymedium" style="margin-top:8px;font-size:90%">'.$langs->trans('SlyPatchPerRowHint').'</div>';

// --- Bottom action bar (card layout) ---
// Each action is a single horizontal card: left band coloured by severity
// (green = safe / orange = warning / red = destructive), middle area holds
// the title + plain-language hint, right area holds the button(s). This
// replaces the older "two red boxes + bare <form>s side-by-side" layout
// that was hard to scan, especially on conflict / recovery screens.
print '<style>
.slypatch-actions { margin:14px 0 6px 0; display:flex; flex-direction:column; gap:6px; }
.slypatch-action  { display:flex; align-items:stretch; gap:10px; padding:9px 12px; border:1px solid #ccc; border-left-width:5px; border-radius:3px; background:#fafafa; }
.slypatch-action.safe   { border-left-color:#4a8; background:#f7fcf7; }
.slypatch-action.warn   { border-left-color:#e8a040; background:#fffaf2; }
.slypatch-action.danger { border-left-color:#c33; background:#fff7f7; }
.slypatch-action .info  { flex:1; min-width:0; }
.slypatch-action .title { font-weight:600; color:#222; font-size:13px; margin-bottom:2px; }
.slypatch-action .hint  { font-size:11px; color:#555; line-height:1.45; }
.slypatch-action .hint code { background:#eee; padding:0 3px; border-radius:2px; font-size:11px; }
.slypatch-action .btns  { flex-shrink:0; display:flex; gap:6px; align-items:center; }
.slypatch-action .btns form { display:inline; margin:0; }
.slypatch-action .btns .butAction,
.slypatch-action .btns .butActionDelete,
.slypatch-action .btns .butActionRefused { margin:0; }
.slypatch-actions .rescan { text-align:right; padding-top:4px; }
.slypatch-actions .rescan a.butAction { margin:0; }
.slypatch-upload-form { display:flex; gap:6px; align-items:center; flex-wrap:wrap; }
.slypatch-upload-form input[type=file] { max-width:240px; }
</style>';

print '<div class="slypatch-actions">';

// Safe — forward apply. Shown when at least one patch is not-applied OR any
// patch is in conflict (the chain will silently skip already-applied rows).
if (($nbNotApplied > 0 || $nbConflict > 0) && $versionOk && $engineAvailable) {
	print '<div class="slypatch-action safe">';
	print '<div class="info">';
	print '<div class="title">📦 '.$langs->trans('SlyPatchActionApplyAll').'</div>';
	print '<div class="hint">'.$langs->trans('SlyPatchActionApplyAllHint').'</div>';
	print '</div>';
	print '<div class="btns">';
	print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchApplyAllConfirmText')).'\');">';
	print '<input type="hidden" name="token" value="'.newToken().'">';
	print '<input type="hidden" name="action" value="applyall">';
	print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchApplyAll', $nbNotApplied).'">';
	print '</form>';
	print '</div>';
	print '</div>';
}

// Safe — manual bundle snapshot. Independent of applyall; useful before
// risky drift edits or before any doc walkthrough that wants a guaranteed
// restore point.
if ($versionOk && $engineAvailable) {
	print '<div class="slypatch-action safe">';
	print '<div class="info">';
	print '<div class="title">📦 '.$langs->trans('SlyPatchActionCreateBundle').'</div>';
	print '<div class="hint">'.$langs->trans('SlyPatchActionCreateBundleHint').'</div>';
	print '</div>';
	print '<div class="btns">';
	print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchCreateBundleConfirmText')).'\');">';
	print '<input type="hidden" name="token" value="'.newToken().'">';
	print '<input type="hidden" name="action" value="bundle_create">';
	print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchCreateBundle').'">';
	print '</form>';
	print '</div>';
	print '</div>';
}

// Danger — restore the most recent bundle. Resolves cross-patch overlap
// (per-patch restore yields a wrong intermediate state for files touched
// by more than one patch).
if ($latestBundle !== '' && $versionOk && $engineAvailable) {
	print '<div class="slypatch-action danger">';
	print '<div class="info">';
	print '<div class="title">⚠ '.$langs->trans('SlyPatchActionRestoreBundle').'</div>';
	print '<div class="hint">'.$langs->trans('SlyPatchActionRestoreBundleHint').' <code>'.htmlspecialchars($latestBundle).'</code> · '.htmlspecialchars(dol_print_date($latestBundleTs, 'dayhour')).'</div>';
	print '</div>';
	print '<div class="btns">';
	print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchRestoreBundleConfirmText', $latestBundle, $latestBundle)).'\');">';
	print '<input type="hidden" name="token" value="'.newToken().'">';
	print '<input type="hidden" name="action" value="restore_bundle">';
	print '<input type="submit" class="butActionDelete" value="'.$langs->trans('SlyPatchRestoreBundle').'">';
	print '</form>';
	print '</div>';
	print '</div>';
}

// Danger — reset conflicting files + re-apply all. Pure local `cp` from
// per-patch backup; refuses if any conflict patch lacks a backup (the
// upload-bundle card below covers that deadlock).
if ($nbConflict > 0 && $versionOk && $engineAvailable) {
	print '<div class="slypatch-action danger">';
	print '<div class="info">';
	print '<div class="title">⚠ '.$langs->trans('SlyPatchActionResetConflict').'</div>';
	print '<div class="hint">'.$langs->trans('SlyPatchActionResetConflictHint');
	if ($missingPerPatchList !== array()) {
		print '<br><strong style="color:#c33">'.$langs->trans('SlyPatchNoBackupNotice', count($missingPerPatchList)).'</strong>';
	}
	print '</div>';
	print '</div>';
	print '<div class="btns">';
	print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchResetConflictConfirmText')).'\');">';
	print '<input type="hidden" name="token" value="'.newToken().'">';
	print '<input type="hidden" name="action" value="resetapplyall_smart">';
	print '<input type="submit" class="butActionDelete" value="'.$langs->trans('SlyPatchResetConflictFilesAndApply').'">';
	print '</form>';
	print '</div>';
	print '</div>';
}

// Warning — upload-bundle recovery path. Only shown when there is at least
// one Conflict patch whose per-patch backup is missing (i.e. the bulk
// reset above would refuse). The operator downloads the target list, builds
// a clean 24.0.1 tar.gz on a pristine git clone, then uploads it. The tool
// restores every target file into DOL_DOCUMENT_ROOT and (re)seeds the
// per-patch backup layer so future Resets become pure local `cp` again.
// Shown for ANY conflict state — including conflicts WITH backups (a backup
// layer seeded from a non-pristine bundle poisons every later Restore, and
// re-uploading a guaranteed-pristine bundle is the only way to displace it).
if ($nbConflict > 0 && $versionOk && $engineAvailable) {
	print '<div class="slypatch-action warn">';
	print '<div class="info">';
	print '<div class="title">📤 '.$langs->trans('SlyPatchActionUploadBundle').'</div>';
	print '<div class="hint">'.$langs->trans('SlyPatchActionUploadBundleHint', count($missingPerPatchList));
	print '<br><a href="'.$_SERVER['PHP_SELF'].'?action=downloadtargetlist&token='.newToken().'">⬇ '.$langs->trans('SlyPatchDownloadTargetList').'</a>';
	print '</div>';
	print '</div>';
	print '<div class="btns">';
	print '<form class="slypatch-upload-form" method="POST" action="'.$_SERVER['PHP_SELF'].'" enctype="multipart/form-data" onsubmit="return confirm(\''.dol_escape_js($langs->transnoentities('SlyPatchUploadBundleConfirmText')).'\');">';
	print '<input type="hidden" name="token" value="'.newToken().'">';
	print '<input type="hidden" name="action" value="upload_bundle">';
	print '<input type="file" name="bundle" accept=".tar.gz,application/gzip,application/x-gzip" required>';
	print '<input type="submit" class="butAction" value="'.$langs->trans('SlyPatchActionUploadBundle').'">';
	print '</form>';
	print '</div>';
	print '</div>';
}

$stCacheAge = (isset($_SESSION['slypatch_stcache']['t']) && !empty($_SESSION['slypatch_stcache']['t'])) ? max(0, time() - $_SESSION['slypatch_stcache']['t']) : 0;
print '<div class="rescan"><span class="opacitymedium" style="font-size:11px">'.$langs->trans('SlyPatchStatusCacheNote', (string) $stCacheAge).'</span> <a class="butAction" href="'.$_SERVER['PHP_SELF'].'?rescan=1">'.$langs->trans('SlyPatchRescan').'</a></div>';
print '</div>';

print '</div>';

llxFooter();
