<?php
/* Copyright (C) 2026 HaoSG Group
 *
 * AES-256-GCM symmetric encryption for TOTP secrets.
 *
 * Why GCM, not CBC:
 *  - GCM is authenticated: any tampering with the ciphertext or IV is detected
 *  - CBC is unauthenticated: we would need to compose our own HMAC and risks padding-oracle bugs
 *  - PHP's openssl extension supports both equally well
 *
 * Key management:
 *  - The 32-byte key lives in llx_const.STRONGAUTH_TOTP_ENC_KEY (base64)
 *  - It is generated by modStrongauth::init() the first time the module is enabled
 *  - Admin can rotate the key from the setup page; rotation re-encrypts all user secrets
 *
 * Ciphertext format (versioned for forward compatibility):
 *   v1:<base64(iv)>:<base64(tag)>:<base64(ciphertext)>
 *   iv length: 12 bytes (GCM recommended)
 *   tag length: 16 bytes
 */

class StrongAuth_Crypto
{
    const VERSION = 'v1';
    const CIPHER  = 'aes-256-gcm';
    const IV_LEN  = 12;   // 96-bit nonce, NIST-recommended for GCM
    const TAG_LEN = 16;   // 128-bit tag, GCM default

    /**
     * Encrypt plaintext (e.g. a base32 TOTP secret) under the module's master key.
     * Throws RuntimeException if the key is missing or malformed.
     */
    public static function encrypt(string $plaintext): string
    {
        $key = self::loadKey();
        $iv  = random_bytes(self::IV_LEN);
        $tag = '';
        $ciphertext = openssl_encrypt(
            $plaintext,
            self::CIPHER,
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            '',              // no AAD
            self::TAG_LEN
        );
        if ($ciphertext === false) {
            throw new RuntimeException('StrongAuth_Crypto::encrypt failed: '.openssl_error_string());
        }
        return self::VERSION.':'
             .base64_encode($iv).':'
             .base64_encode($tag).':'
             .base64_encode($ciphertext);
    }

    /**
     * Decrypt a ciphertext produced by encrypt(). Returns null on any failure
     * (wrong key, tampered ciphertext, wrong version, bad encoding).
     */
    public static function decrypt(string $payload): ?string
    {
        $parts = explode(':', $payload);
        if (count($parts) !== 4 || $parts[0] !== self::VERSION) {
            return null;
        }
        $iv  = base64_decode($parts[1], true);
        $tag = base64_decode($parts[2], true);
        $ct  = base64_decode($parts[3], true);
        if ($iv === false || $tag === false || $ct === false) {
            return null;
        }
        if (strlen($iv) !== self::IV_LEN || strlen($tag) !== self::TAG_LEN) {
            return null;
        }
        $key = self::loadKey();
        $plaintext = openssl_decrypt(
            $ct,
            self::CIPHER,
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag
        );
        return $plaintext === false ? null : $plaintext;
    }

    /**
     * Rotate the master key. Reads all encrypted TOTP secrets, re-encrypts
     * them under a fresh key, writes the new key into llx_const, then
     * updates every row in a single transaction.
     *
     * Returns the new key (base64). Caller is responsible for backing it up.
     *
     * @return array{rows:int, new_key:string}
     */
    public static function rotateKey(DoliDB $db, int $entity): array
    {
        $newKey = base64_encode(random_bytes(32));

        $db->begin();
        try {
            // Save the OLD key on the stack so we can decrypt existing rows.
            $oldKey = self::loadKey();

            // Temporarily install the NEW key for the encryption call below.
            self::$cachedKey = base64_decode($newKey);

            $sql = "SELECT rowid, secret_enc FROM ".MAIN_DB_PREFIX."strongauth_totp WHERE entity = ".(int) $entity;
            $res = $db->query($sql);
            $count = 0;
            while ($row = $db->fetch_object($res)) {
                $plain = self::decryptWith($oldKey, $row->secret_enc);
                if ($plain === null) {
                    // Skip rows that fail to decrypt — they will need to be re-enrolled.
                    continue;
                }
                $newCipher = self::encryptWith(self::$cachedKey, $plain);
                $upd = "UPDATE ".MAIN_DB_PREFIX."strongauth_totp SET secret_enc = '".$db->escape($newCipher)."' WHERE rowid = ".(int) $row->rowid;
                if (!$db->query($upd)) {
                    throw new RuntimeException('Rotate failed at rowid='.$row->rowid.': '.$db->lasterror);
                }
                $count++;
            }

            dol_include_once('/core/lib/admin.lib.php');
            dolibarr_set_const($db, 'STRONGAUTH_TOTP_ENC_KEY', $newKey, '', 0, '', $entity);

            $db->commit();
            self::$cachedKey = null;
            return ['rows' => $count, 'new_key' => $newKey];
        } catch (Throwable $e) {
            $db->rollback();
            self::$cachedKey = null;
            throw $e;
        }
    }

    // -----------------------------------------------------------------------
    // internals
    // -----------------------------------------------------------------------

    /** @var string|null  Cached key for the request, used during rotation. */
    private static $cachedKey = null;

    private static function loadKey(): string
    {
        if (self::$cachedKey !== null) {
            return self::$cachedKey;
        }
        global $conf;
        if (empty($conf->global->STRONGAUTH_TOTP_ENC_KEY)) {
            throw new RuntimeException('STRONGAUTH_TOTP_ENC_KEY is missing — re-enable the module or run a key rotation.');
        }
        $key = base64_decode($conf->global->STRONGAUTH_TOTP_ENC_KEY, true);
        if ($key === false || strlen($key) !== 32) {
            throw new RuntimeException('STRONGAUTH_TOTP_ENC_KEY is malformed (must be base64 of 32 raw bytes).');
        }
        return $key;
    }

    /** Decrypt with an explicit key, bypassing the cached one. Used during rotation. */
    private static function decryptWith(string $key, string $payload): ?string
    {
        $parts = explode(':', $payload);
        if (count($parts) !== 4 || $parts[0] !== self::VERSION) {
            return null;
        }
        $iv  = base64_decode($parts[1], true);
        $tag = base64_decode($parts[2], true);
        $ct  = base64_decode($parts[3], true);
        if (!$iv || !$tag || !$ct) {
            return null;
        }
        $pt = openssl_decrypt($ct, self::CIPHER, $key, OPENSSL_RAW_DATA, $iv, $tag);
        return $pt === false ? null : $pt;
    }

    /** Encrypt with an explicit key. */
    private static function encryptWith(string $key, string $plaintext): string
    {
        $iv = random_bytes(self::IV_LEN);
        $tag = '';
        $ct = openssl_encrypt($plaintext, self::CIPHER, $key, OPENSSL_RAW_DATA, $iv, $tag);
        if ($ct === false) {
            throw new RuntimeException('StrongAuth_Crypto encryptWith failed');
        }
        return self::VERSION.':'.base64_encode($iv).':'.base64_encode($tag).':'.base64_encode($ct);
    }
}
